module.exports = {
  REPORT_INCIDENT: 'report_incident',
  STEWARD_REPORT_INCIDENT: 'steward_report_incident',
  INCIDENT_DIVISION_PREFIX: 'incident_division',
  STEWARD_INCIDENT_DIVISION_PREFIX: 'steward_incident_division',
  INCIDENT_REASON_PREFIX: 'incident_reason',
  STEWARD_INCIDENT_REASON_PREFIX: 'steward_incident_reason',
  INCIDENT_REASON_SELECT: 'incident_reason',
  INCIDENT_CULPRIT_SELECT: 'incident_culprit_select',
  STEWARD_REPORTER_SELECT: 'steward_incident_reporter_select',
  STEWARD_CULPRIT_SELECT: 'steward_incident_culprit_select',
  APPEAL_RESOLVED_PREFIX: 'appeal_resolved',
  INCIDENT_MODAL: 'incident_modal',
  APPEAL_MODAL: 'appeal_modal',
  FINALIZE_MODAL: 'finalize_modal',
  FINALIZE_CONFIRM: 'finalize_confirm',
  FINALIZE_CANCEL: 'finalize_cancel',
  INCIDENT_REVIEW_EDIT: 'incident_review_edit',
  INCIDENT_REVIEW_CONFIRM: 'incident_review_confirm',
  FINALIZE_VOTES: 'finalize_votes',
  VOTE_CAT_PREFIX: 'vote_cat',
  VOTE_REPORTER_CAT_PREFIX: 'vote_reporter_cat',
  VOTE_PLUS: 'vote_plus',
  VOTE_MINUS: 'vote_minus',
  VOTE_REPORTER_PLUS: 'vote_reporter_plus',
  VOTE_REPORTER_MINUS: 'vote_reporter_minus'
};
